// Package ops declares the full godot-ai-cli command surface: one OpSpec
// per plugin operation, generated by hand from the upstream tool→plugin
// command mapping (src/godot_ai/handlers/*.py) and kept honest by parity
// tests against the vendored plugin's register_lazy lines.
package ops

import (
	"fmt"
	"time"
)

// Timeout ladder, mirrored from upstream (protocol/timeouts.py, the
// plugin's deferred budgets in dispatcher.gd, and the per-call client
// timeouts in handlers/game.py).
const (
	// DefaultTimeout is the per-op default (the daemon's own default
	// execute budget is 8s too).
	DefaultTimeout = 8 * time.Second
	// TestRunTimeout mirrors TEST_RUN_TIMEOUT_SEC.
	TestRunTimeout = 300 * time.Second
	// ScreenshotTimeout mirrors the take_screenshot deferred budget.
	ScreenshotTimeout = 30 * time.Second
	// ScanTimeout mirrors the scan_filesystem deferred budget.
	ScanTimeout = 30 * time.Second
	// GameTimeout mirrors GAME_COMMAND_TIMEOUT_SEC (game_eval and
	// game_command share it).
	GameTimeout = 15 * time.Second
	// BatchTimeout is the batch_execute budget (rollback of a long batch
	// legitimately outlasts a single op).
	BatchTimeout = 30 * time.Second
	// InputSequenceTimeout mirrors INPUT_SEQUENCE_TIMEOUT_SEC: the
	// frame-timed sequence drives the game forward one frame per step.
	InputSequenceTimeout = 30 * time.Second
	// RecordTimeout mirrors RECORD_FRAMES_TIMEOUT_SEC plus margin: frame-aligned
	// burst capture takes one readback per game frame.
	RecordTimeout = 75 * time.Second
)

// Param kinds accepted by ParamSpec.Kind.
const (
	KindString = "string"
	KindInt    = "int"
	KindFloat  = "float"
	KindBool   = "bool"
	KindJSON   = "json" // raw JSON value (array, object, string, number)
)

// OpSpec declares one CLI leaf command bound to a plugin command.
type OpSpec struct {
	Domain        string        // CLI group, e.g. "node"
	Name          string        // CLI op name (kebab-case), e.g. "create"
	PluginCommand string        // wire command, e.g. "create_node"
	Summary       string        // English one-liner for help
	Timeout       time.Duration // per-op timeout from the upstream ladder
	Write         bool          // true → readiness gate (write:true on execute)
	Params        []ParamSpec   // declared flags
	// ResponseNote, when non-empty, is appended to the -h long help as a
	// "Response:" section documenting the payload fields (agents otherwise
	// discover response keys by trial and error).
	ResponseNote string
	// WrapOp, when non-empty, routes through a wrapper plugin command:
	// the wire params become {"op": WrapOp, "params": <collected>}.
	// Used by the game domain (everything goes through game_command).
	WrapOp string
}

// ParamSpec declares one typed flag on an op leaf command.
type ParamSpec struct {
	Flag     string // CLI flag name (kebab-case), e.g. "parent-path"
	Param    string // wire param key, e.g. "parent_path"
	Kind     string // string|int|float|bool|json
	Required bool
	Default  string // flag default (empty = kind zero value)
	Usage    string // English help text
}

// HandWiredLeaves documents the CLI leaves that are NOT OpSpec-backed
// because they talk to the daemon, not to a plugin command (or route
// through a dynamic command name, or — the image group — run fully local).
var HandWiredLeaves = []string{
	"session list",      // daemon-side: GET /godot-ai/cli/sessions
	"session activate",  // daemon-side: POST /godot-ai/cli/activate
	"custom list",       // daemon-side: custom-tool catalog cached from plugin events
	"custom invoke",     // dynamic plugin command custom_tool:<name>
	"call",              // escape hatch for arbitrary plugin commands
	"image palette",     // local: pure-Go texture palette analysis, no daemon
	"image probe",       // local: pure-Go pixel sampling, no daemon
	"image grid-detect", // local: pure-Go sprite-sheet grid detection, no daemon
}

// InternalOnlySpec documents a registered plugin command that is
// deliberately NOT exposed as a CLI subcommand.
type InternalOnlySpec struct {
	Command string
	Reason  string
}

// InternalOnly lists registered plugin commands with no CLI subcommand.
// The three client commands are registered in upstream but guarded off in
// this fork (ForkConfig.mcp_client_config_disabled); they are listed here
// so the parity test's set math stays exact.
var InternalOnly = []InternalOnlySpec{
	{Command: "configure_client", Reason: "unregistered in the godot-ai-cli fork — client configuration is a CLI/skill concern, not an editor operation"},
	{Command: "remove_client", Reason: "unregistered in the godot-ai-cli fork — client configuration is a CLI/skill concern, not an editor operation"},
	{Command: "check_client_status", Reason: "unregistered in the godot-ai-cli fork — client configuration is a CLI/skill concern, not an editor operation"},
}

// domainOrder fixes the help/aggregation order of domain groups.
var domainOrder = []string{
	"editor", "scene", "node", "script", "project", "session", "test",
	"animation", "material", "audio", "particle", "camera", "signal",
	"input-map", "game", "autoload", "filesystem", "theme", "ui",
	"resource", "api", "tilemap", "tileset", "gridmap", "csg", "custom",
	"batch", "logs",
}

// domainSummaries backs the parent-group help text.
var domainSummaries = map[string]string{
	"editor":     "Editor state, selection, screenshots, and lifecycle",
	"scene":      "Scene tree inspection and scene file management",
	"node":       "Create, find, mutate, and organize scene nodes",
	"script":     "Create, patch, read, and attach GDScript files",
	"project":    "Project settings and running the project",
	"session":    "Connected editor sessions (daemon-side, no plugin command)",
	"test":       "Run GDScript test suites in the editor",
	"animation":  "AnimationPlayers, animations, tracks, and presets",
	"material":   "Material resources and shader parameters",
	"audio":      "Audio players, streams, and playback",
	"particle":   "Particle nodes, process materials, and presets",
	"camera":     "Camera nodes, 2D follow/limits, and presets",
	"signal":     "List, connect, and disconnect node signals",
	"input-map":  "Project input actions and event bindings",
	"game":       "Introspect and drive the RUNNING game (input, scene reads)",
	"autoload":   "Project autoload singletons",
	"filesystem": "Project filesystem reads, writes, reimport, and scan",
	"theme":      "Theme resources and styleboxes",
	"ui":         "Control layout, text, anchors, and draw recipes",
	"resource":   "Generic resource search/load/create plus typed creators",
	"api":        "ClassDB metadata for Godot classes",
	"tilemap":    "TileMapLayer cell editing and queries",
	"tileset":    "TileSet atlas inspection",
	"gridmap":    "GridMap item editing and queries",
	"csg":        "CSG shape creation and operations",
	"custom":     "Third-party custom tools registered in the editor",
	"batch":      "Run multiple plugin commands atomically",
	"logs":       "Plugin / game / editor log buffers",
}

// All aggregates every domain's op table in the fixed domain order.
func All() []OpSpec {
	var out []OpSpec
	for _, domain := range domainOrder {
		out = append(out, domainOps(domain)...)
	}
	return out
}

// Domains returns the domain names in display order.
func Domains() []string {
	return append([]string(nil), domainOrder...)
}

// DomainSummary returns the parent-group help one-liner for a domain.
func DomainSummary(domain string) string {
	return domainSummaries[domain]
}

// domainOps resolves one domain's table.
func domainOps(domain string) []OpSpec {
	switch domain {
	case "editor":
		return editorOps()
	case "scene":
		return sceneOps()
	case "node":
		return nodeOps()
	case "script":
		return scriptOps()
	case "project":
		return projectOps()
	case "test":
		return testOps()
	case "animation":
		return animationOps()
	case "material":
		return materialOps()
	case "audio":
		return audioOps()
	case "particle":
		return particleOps()
	case "camera":
		return cameraOps()
	case "signal":
		return signalOps()
	case "input-map":
		return inputMapOps()
	case "game":
		return gameOps()
	case "autoload":
		return autoloadOps()
	case "filesystem":
		return filesystemOps()
	case "theme":
		return themeOps()
	case "ui":
		return uiOps()
	case "resource":
		return resourceOps()
	case "api":
		return apiOps()
	case "tilemap":
		return tilemapOps()
	case "tileset":
		return tilesetOps()
	case "gridmap":
		return gridmapOps()
	case "csg":
		return csgOps()
	case "batch":
		return batchOps()
	case "logs":
		return logsOps()
	default:
		return nil // session and custom are hand-wired in the CLI layer
	}
}

// Lookup finds one op by domain and name.
func Lookup(domain, name string) (OpSpec, bool) {
	for _, op := range All() {
		if op.Domain == domain && op.Name == name {
			return op, true
		}
	}
	return OpSpec{}, false
}

// ByDomain groups All() under its domain names (fixed order preserved).
func ByDomain() map[string][]OpSpec {
	out := map[string][]OpSpec{}
	for _, op := range All() {
		out[op.Domain] = append(out[op.Domain], op)
	}
	return out
}

// SortedDomainsWithOps returns domain names that have OpSpec-backed ops.
func SortedDomainsWithOps() []string {
	present := map[string]bool{}
	for _, op := range All() {
		present[op.Domain] = true
	}
	var out []string
	for _, d := range domainOrder {
		if present[d] {
			out = append(out, d)
		}
	}
	return out
}

// ps / pi / pf / pb / pj are ParamSpec constructors keeping the domain
// tables compact (string / int / float / bool / json kinds).

func ps(flag, param string, required bool, def, usage string) ParamSpec {
	return ParamSpec{Flag: flag, Param: param, Kind: KindString, Required: required, Default: def, Usage: usage}
}

func pi(flag, param string, required bool, def, usage string) ParamSpec {
	return ParamSpec{Flag: flag, Param: param, Kind: KindInt, Required: required, Default: def, Usage: usage}
}

func pf(flag, param string, required bool, def, usage string) ParamSpec {
	return ParamSpec{Flag: flag, Param: param, Kind: KindFloat, Required: required, Default: def, Usage: usage}
}

func pb(flag, param string, required bool, def, usage string) ParamSpec {
	return ParamSpec{Flag: flag, Param: param, Kind: KindBool, Required: required, Default: def, Usage: usage}
}

func pj(flag, param string, required bool, usage string) ParamSpec {
	return ParamSpec{Flag: flag, Param: param, Kind: KindJSON, Required: required, Usage: usage}
}

// Validate sanity-checks one spec; the convention tests run it over All().
func (op OpSpec) Validate() error {
	if op.Domain == "" || op.Name == "" || op.PluginCommand == "" || op.Summary == "" {
		return fmt.Errorf("op %s/%s: Domain, Name, PluginCommand, Summary are required", op.Domain, op.Name)
	}
	if op.Timeout < time.Second || op.Timeout > 600*time.Second {
		return fmt.Errorf("op %s/%s: timeout %s outside [1s, 600s]", op.Domain, op.Name, op.Timeout)
	}
	for _, p := range op.Params {
		switch p.Kind {
		case KindString, KindInt, KindFloat, KindBool, KindJSON:
		default:
			return fmt.Errorf("op %s/%s: param %s has invalid kind %q", op.Domain, op.Name, p.Flag, p.Kind)
		}
		if p.Flag == "" || p.Param == "" {
			return fmt.Errorf("op %s/%s: param with empty Flag or Param", op.Domain, op.Name)
		}
	}
	return nil
}
